version: "3.9"

services:

  backend:
    container_name: backend
    build:
      dockerfile: ./weather_app/docker/Dockerfile
    command: sh /backend/docker/entrypoint.sh
    volumes:
      - ./weather_app:/backend
    ports:
      - "8080:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    container_name: db
    image: postgres:16.1-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis:7.0.15-alpine
    ports:
      - "6379:6379"

  tgbot:
    container_name: tgbot
    build:
      dockerfile: ./weather_bot/docker/Dockerfile
    command: python app.py
    volumes:
      - ./weather_bot:/bot
    env_file:
      - .env

