# Generated by Django 5.0.1 on 2024-01-11 14:49
import json

from django.db import migrations, models


def create_data(apps, schema_editor):
    Coordinate = apps.get_model('weather', 'Coordinate')

    coordinates: list = []
    coordinates_raw: dict = json.loads(open('./coordinates.json').read())
    for coordinate in coordinates_raw:
        coordinate_obj = Coordinate(
            name=coordinate['name'],
            latitude=coordinate['coords']['lat'],
            longitude=coordinate['coords']['lon'],
        )
        coordinates.append(coordinate_obj)

    Coordinate.objects.bulk_create(coordinates, batch_size=1000)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Долгота')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование города')),
            ],
        ),
        migrations.RunPython(create_data)
    ]
