# Generated by Django 5.0.1 on 2024-01-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_coordinate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Наименование города'),
        ),
        migrations.AddIndex(
            model_name='coordinate',
            index=models.Index(fields=['name'], name='weather_coo_name_aeb04b_idx'),
        ),
    ]
