# Generated by Django 5.0.1 on 2024-01-11 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_coordinate_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinate',
            options={'verbose_name': 'Координаты', 'verbose_name_plural': 'Координаты'},
        ),
    ]
